// Automatically generated by astro-icon
// 2820b6247265e0cc82ffc8e855120af243f2799b8cc2fc5c6dc5e92d1d9d7e3d

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrowupright"
		| "astro"
		| "astro-logo-light"
		| "checkmark"
		| "copy"
		| "css"
		| "docker"
		| "figma"
		| "gemini"
		| "github"
		| "go"
		| "googleads"
		| "googleanalytics"
		| "googletagmanager"
		| "hamburger"
		| "html"
		| "illustrator"
		| "javascript"
		| "jest"
		| "linehorizontal"
		| "next"
		| "nextjslogo"
		| "node"
		| "photoshop"
		| "prisma"
		| "reactjs"
		| "reactquery"
		| "redux"
		| "slash"
		| "tailwind"
		| "typescript"
		| "vite"
		| "whatsapp";
}