// Automatically generated by astro-icon
// 42bcccf318a98ce5936a0ce3c5372da5c56d5b1a41a95a9d90ffcf15c1ab58ce

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrowupright"
		| "astro"
		| "astro-logo-light"
		| "checkmark"
		| "copy"
		| "css"
		| "docker"
		| "figma"
		| "gemini"
		| "github"
		| "go"
		| "googleads"
		| "googleanalytics"
		| "googletagmanager"
		| "html"
		| "illustrator"
		| "javascript"
		| "jest"
		| "linehorizontal"
		| "next"
		| "nextjslogo"
		| "node"
		| "photoshop"
		| "prisma"
		| "reactjs"
		| "reactquery"
		| "redux"
		| "slash"
		| "tailwind"
		| "typescript"
		| "vite"
		| "whatsapp";
}