// Automatically generated by astro-icon
// fcbed6c78fe9e8a2d8d018b56d8b3f0fb51cbdf2dbfc165608ca43811939957a

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrowupright"
		| "slash"
		| "whatsapp";
}